### PR TITLE
Leverage Git Submodules to pull in required libraries.

### PR DESCRIPTION
**Pull request by zfields**
This will address the confusion surrounding the multiple repositories, and bring everything together so it will just work.

### CODE REVIEW

**Comment by zfields** [comment]
I haven't heard anything about this, but I just updated the branch on the off chance you wanted to pull it. ;)

**Comment by ToniCorinne** [comment]
Sorry for the radio silence on this! We actually decided to go with subtrees as our method of addressing issues like this, due to having too many 'off/exception' cases in our system that don't really work well with submodules. I've been slowly updating all the products as we come across them that need this update, but I will fix this one asap. Thanks again for keeping us on track!

**Comment by zfields** [comment]
If I can update my commit to match your style and get pulled, I'm happy to do it. I would love to have a commit on your repo! Thanks for the quick reply,
Zak

**Comment by ToniCorinne** [comment]
Hey @zfields - Sorry for the delay again! If you'd like to do the pull request with the subtrees, we'd like it to be in the following format:

* Libraries/Arduino/MPL3115A2
* Libraries/Arduino/HTU21D

For adding each subtree, you'd use the following command:
     *git subtree add -P Libraries/Arduino/[LibraryName] --squash [LibraryRepositoryAddress] master*

**Comment by nseidle** [comment]
Hi zfields - thank you again for your help making this code better. Arduino has diverged enough over the past few years with how a user installs a library that I believe this pull request is no longer relevant. I'm cleaning up the repo and tutorial. If you see anything that could use improvement please let us know!

**Pull request closed without merging**
